# Generated by Django 2.2.4 on 2022-06-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('Enrollment_Number', models.CharField(max_length=100)),
                ('Regional_Centre_Code', models.CharField(max_length=100)),
                ('Regional_Centre_Name', models.CharField(max_length=100)),
                ('Study_Centre_Code', models.CharField(max_length=100)),
                ('Study_Centre_Name', models.CharField(max_length=100)),
                ('Session', models.CharField(max_length=100)),
                ('temporary_block', models.CharField(max_length=100)),
                ('permanent_block', models.CharField(max_length=100)),
                ('timout', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(blank=True, max_length=30)),
                ('free_user_file', models.FileField(blank=True, upload_to='media/documents/free/')),
                ('paid_user_file', models.FileField(blank=True, upload_to='media/documents/paid/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.CharField(blank=True, choices=[('BACHELORS', 'BACHELORS'), ('MASTERS', 'MASTERS'), ('CERTIFICATE', 'CERTIFICATE'), ('DEGEE', 'DEGEE'), ('PG', 'PG'), ('DIPLOMA', 'DIPLOMA')], max_length=9)),
                ('year', models.IntegerField(blank=True)),
                ('file_type', models.CharField(blank=True, choices=[('ASSIGNMENT', 'ASSIGNMENT'), ('QUESTION_PAPER', 'QUESTION_PAPER'), ('WORKBOOK', 'WORKBOOK'), ('EVENTS', 'EVENTS')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_source', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField(blank=True)),
                ('object_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Objects')),
                ('user_paid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ExtendedUser')),
            ],
        ),
    ]
