# Generated by Django 2.2.4 on 2022-06-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220613_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='event_date',
        ),
    ]
