# Generated by Django 2.2.4 on 2022-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220613_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200)),
                ('answer', models.DateTimeField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
