# Generated by Django 2.2.4 on 2022-06-16 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220616_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='free_user_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='paid_user_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
