# Generated by Django 2.2.4 on 2022-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220616_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
