# Generated by Django 2.2.4 on 2022-06-27 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
