# Generated by Django 2.2.4 on 2022-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_extendeduser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.CharField(blank=True, choices=[('SLIDER', 'SLIDER'), ('ABOUT', 'ABOUT')], max_length=9),
        ),
    ]
