# Generated by Django 2.2.4 on 2022-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_objects_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='course_id',
            field=models.CharField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
    ]
