# Generated by Django 2.2.4 on 2022-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_objects_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='Last_name',
        ),
        migrations.AlterField(
            model_name='objects',
            name='course_id',
            field=models.CharField(max_length=30),
        ),
    ]
