# Generated by Django 2.2.4 on 2022-07-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220702_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='Gender',
            new_name='course',
        ),
    ]
