# Generated by Django 4.0.5 on 2022-07-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220702_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='course_category',
            field=models.CharField(blank=True, choices=[('BACHELORS', 'BACHELORS'), ('MASTERS', 'MASTERS'), ('CERTIFICATE', 'CERTIFICATE'), ('DEGEE', 'DEGEE'), ('PG', 'PG'), ('DIPLOMA', 'DIPLOMA')], max_length=20),
        ),
    ]
