# Generated by Django 4.0.5 on 2022-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_objects_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
