# Generated by Django 4.0.5 on 2022-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_extendeduser_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='timout',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
