# Generated by Django 4.0.5 on 2022-07-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_remove_extendeduser_timout_extendeduser_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objects'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.extendeduser'),
        ),
    ]
