# Generated by Django 4.0.5 on 2022-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_extendeduser_user_alter_payment_object_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='redirect_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
