# Generated by Django 3.2.1 on 2022-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220706_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
