# Generated by Django 3.2.1 on 2022-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_extendeduser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
